//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <System.Classes.hpp>
#include <Vcl.Controls.hpp>
#include <Vcl.StdCtrls.hpp>
#include <Vcl.Forms.hpp>
#include <Vcl.Buttons.hpp>
#include <Vcl.ExtCtrls.hpp>
#include <Vcl.ComCtrls.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE で管理されるコンポーネント
	TPanel *Panel10;
	TComboBox *CW_Tx_Port;
	TBitBtn *F1_Exit;
	TBitBtn *Search;
	TComboBox *Cont_Tx_Port;
	TComboBox *Backscatter_Rx_Port;
	TPanel *Panel20;
	TEdit *CW_Tx_Freq;
	TLabel *Label1;
	TLabel *Label2;
	TEdit *Backscatter_Rx_Freq;
	TPanel *Panel3;
	TPanel *Panel4;
	TLabel *Label5;
	TLabel *Label6;
	TLabel *Label9;
	TEdit *Tag1_Tim;
	TLabel *Label10;
	TEdit *Tag1_Vbat;
	TLabel *Label11;
	TEdit *Tag1_Temp;
	TLabel *Label12;
	TEdit *Tag1_Hum;
	TLabel *Label13;
	TEdit *Tag1_Pres;
	TEdit *Tag1_Alarm;
	TLabel *Label25;
	TComboBox *Cont_Tx_Freq;
	TPanel *Panel6;
	TPanel *Panel21;
	TLabel *Label16;
	TLabel *Label17;
	TLabel *Label18;
	TComboBox *Step_Freq;
	TComboBox *Step_Num;
	TComboBox *Interval;
	TEdit *CW_Tx_Power;
	TLabel *Label3;
	TUpDown *UpDown1;
	TButton *CW_TxRx_Start;
	TTimer *Timer1;
	TButton *CW_TxRx_Stop;
	TLabel *Label4;
	TEdit *Cont_Tx_Power;
	TUpDown *UpDown2;
	TButton *Cont_Tx_Setup;
	TEdit *SrcMAC;
	TLabel *Label14;
	TLabel *Label15;
	TEdit *SrcPAN;
	TPanel *Panel1;
	TEdit *Edit2;
	TPanel *Panel2;
	TEdit *Edit1;
	TLabel *Label19;
	TLabel *Label20;
	TLabel *Label21;
	TEdit *NowCwFreq;
	TEdit *Tag1_Rssi;
	TLabel *Label22;
	TEdit *Tag1_MAC;
	TLabel *Label23;
	TEdit *Tag1_Count;
	TLabel *Label7;
	TComboBox *AlarmInterval;
	TPanel *Panel5;
	TPanel *Panel7;
	TPanel *Panel8;
	TPanel *Panel9;
	TLabel *Label8;
	TLabel *Label24;
	TLabel *Label26;
	TLabel *Label27;
	TLabel *Label28;
	TLabel *Label29;
	TLabel *Label30;
	TLabel *Label31;
	TLabel *Label32;
	TEdit *Tag2_Tim;
	TEdit *Tag2_Vbat;
	TEdit *Tag2_Temp;
	TEdit *Tag2_Hum;
	TEdit *Tag2_Pres;
	TEdit *Tag2_Alarm;
	TEdit *Tag2_Rssi;
	TEdit *Tag2_MAC;
	TEdit *Tag2_Count;
	TPanel *Panel11;
	TLabel *Label33;
	TLabel *Label34;
	TLabel *Label35;
	TLabel *Label36;
	TLabel *Label37;
	TLabel *Label38;
	TLabel *Label39;
	TLabel *Label40;
	TLabel *Label41;
	TEdit *Tag3_Tim;
	TEdit *Tag3_Vbat;
	TEdit *Tag3_Temp;
	TEdit *Tag3_Hum;
	TEdit *Tag3_Pres;
	TEdit *Tag3_Alarm;
	TEdit *Tag3_Rssi;
	TEdit *Tag3_MAC;
	TEdit *Tag3_Count;
	TPanel *Panel12;
	TLabel *Label42;
	TLabel *Label43;
	TLabel *Label44;
	TLabel *Label45;
	TLabel *Label46;
	TLabel *Label47;
	TLabel *Label48;
	TLabel *Label49;
	TLabel *Label50;
	TEdit *Tag4_Tim;
	TEdit *Tag4_Vbat;
	TEdit *Tag4_Temp;
	TEdit *Tag4_Hum;
	TEdit *Tag4_Pres;
	TEdit *Tag4_Alarm;
	TEdit *Tag4_Rssi;
	TEdit *Tag4_MAC;
	TEdit *Tag4_Count;
	TPanel *Panel13;
	TButton *ClearLog;
	TPanel *Panel14;
	TLabel *Label51;
	TLabel *Label52;
	TLabel *Label53;
	TLabel *Label54;
	TLabel *Label55;
	TLabel *Label56;
	TLabel *Label57;
	TLabel *Label58;
	TLabel *Label59;
	TEdit *Tag5_Tim;
	TEdit *Tag5_Vbat;
	TEdit *Tag5_Temp;
	TEdit *Tag5_Hum;
	TEdit *Tag5_Pres;
	TEdit *Tag5_Alarm;
	TEdit *Tag5_Rssi;
	TEdit *Tag5_MAC;
	TEdit *Tag5_Count;
	TPanel *Panel15;
	TLabel *Label60;
	TLabel *Label61;
	TLabel *Label62;
	TLabel *Label63;
	TLabel *Label64;
	TLabel *Label65;
	TLabel *Label66;
	TLabel *Label67;
	TLabel *Label68;
	TEdit *Tag6_Tim;
	TEdit *Tag6_Vbat;
	TEdit *Tag6_Temp;
	TEdit *Tag6_Hum;
	TEdit *Tag6_Pres;
	TEdit *Tag6_Alarm;
	TEdit *Tag6_Rssi;
	TEdit *Tag6_MAC;
	TEdit *Tag6_Count;
	TPanel *Panel16;
	TLabel *Label69;
	TLabel *Label70;
	TLabel *Label71;
	TLabel *Label72;
	TLabel *Label73;
	TLabel *Label74;
	TLabel *Label75;
	TLabel *Label76;
	TLabel *Label77;
	TEdit *Tag7_Tim;
	TEdit *Tag7_Vbat;
	TEdit *Tag7_Temp;
	TEdit *Tag7_Hum;
	TEdit *Tag7_Pres;
	TEdit *Tag7_Alarm;
	TEdit *Tag7_Rssi;
	TEdit *Tag7_MAC;
	TEdit *Tag7_Count;
	TPanel *Panel17;
	TLabel *Label78;
	TLabel *Label79;
	TLabel *Label80;
	TLabel *Label81;
	TLabel *Label82;
	TLabel *Label83;
	TLabel *Label84;
	TLabel *Label85;
	TLabel *Label86;
	TEdit *Tag8_Tim;
	TEdit *Tag8_Vbat;
	TEdit *Tag8_Temp;
	TEdit *Tag8_Hum;
	TEdit *Tag8_Pres;
	TEdit *Tag8_Alarm;
	TEdit *Tag8_Rssi;
	TEdit *Tag8_MAC;
	TEdit *Tag8_Count;
	TLabel *Label87;
	TComboBox *InitAlarm;
	TEdit *InitTime;
	TEdit *InitSetTime;
	TLabel *Label88;
	TLabel *Label89;
	void __fastcall F1_Create(TObject *Sender);
	//void __fastcall Tx_Freq_SetClick(TObject *Sender);
	void __fastcall CW_TxRx_StartClick(TObject *Sender);
	void __fastcall F1_ExitClick(TObject *Sender);
	void __fastcall Timer1Timer(TObject *Sender);
	void __fastcall CW_TxRx_StopClick(TObject *Sender);
	//void __fastcall Time_SyncClick(TObject *Sender);
	void __fastcall Cont_Tx_SetupClick(TObject *Sender);
	//void __fastcall InitSleepClick(TObject *Sender);
	void __fastcall ClearLogClick(TObject *Sender);
	void __fastcall SearchClick(TObject *Sender);
private:	// ユーザー宣言
public:		// ユーザー宣言
	__fastcall TForm1(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
